### ISSUE TITLE
circleci attach_workspace fails on latest image

### ISSUE THREAD

**Issue by alexsn** [testimio/docker-cli#3]
It seems 27f743aae1c1acd47ecc85af1b1df16a2664a0f0 breaks circleci attach_workspace step with the following error:
> Downloading workspace layers
> 
> Error downloading workspace layer for job 4e592f67-b2a9-471e-b50f-69f942aa736a. If this is a re-run of an old job, the workspace may have expired.: RequestError: send request failed
> caused by: Get https://circle-production-customer-artifacts.s3.amazonaws.com/?list-type=2&prefix=picard%2F5da633ddda1d4a7f21aa751d%2Fworkflows%2Fworkspaces%2F2f578652-50a5-4992-b0bd-ebd9010c6242%2F0%2F4e592f67-b2a9-471e-b50f-69f942aa736a: x509: certificate signed by unknown authority

In addition it's not possible to use the previous image from dockerhub as you only maintain the `latest` tag.

**Comment by ronkorland** [comment]
1. I created a new tag: `node-8` if you want to test with node v8 (NodeJS v8 is not supported anymore)
2. The error you added is looking like an error from CircleCI - my recommended to you to open a ticket to CircleCI with the error message

**Comment by alexsn** [comment]
Issue still occurring with previous image, so it looks unrelated.

**Comment by alexsn** [comment]
Correction, issue is resolved when reverting to `node-8`. Probably related to ca-certificates coming from base image (related to circleci [resolution](https://support.circleci.com/hc/en-us/articles/360016505753-Resolve-Certificate-Signed-By-Unknown-Authority-error-in-Alpine-images)).

**Comment by ronkorland** [comment]
I added `ca-certificates` packages to the Dockerfile, can you please try again with `latest` tag?
